name: release simple.vue

# 执行action的条件
# 当main分支 push事件触发时执行任务
on:
  push:
    branches: [main]

env:
  RELEASE_TAG: v0.0.6  # ⭐ 全局变量

jobs:
  release-html: # job名称
    runs-on: ubuntu-latest # 在GitHub托管的新虚拟机上执行(https://docs.github.com/zh/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idruns-on)

    permissions:
      contents: write  # ⚠️ 创建 tag / release 必须

    steps:

      # 创建 Tag
      - name: Create git tag
        uses: actions/github-script@v7
        with:
          script: |
            const tag = process.env.RELEASE_TAG
            await github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/${tag}`,
              sha: context.sha
            })

      # 3️⃣ 创建 GitHub Release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          name: Release ${{ env.RELEASE_TAG }}
          generate_release_notes: true

